### ISSUE TITLE
Guidance on Macos install

### ISSUE THREAD

**Issue by nerdinthenord** [dd-center/obs-streamlink#18] opened 2022-01-10 15:12 UTC
Any chance i can get some input on using this on Macos?

**Comment by cqjjjzr** [comment] 2022-01-10 15:13
duplicate of #2, not to be fixed recently. sry for the inconvenience

**Closed as completed by cqjjjzr** 2022-01-10 15:13 UTC

**Comment by cqjjjzr** [comment] 2022-01-10 15:18
got a buddy for help on macOS environment, see #19
